[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Solutions to the Advent of Code 2021 puzzles"
edition = "2021"

[dependencies]
itertools = "0.10"
thiserror = "1.0"
